"""Map every playable word to its nearest emoji and write the static lookup + manifest.

Pure, deterministic pipeline:

    (dictionary.json, emoji_vocab.json, MODEL_ID) -> word_emoji.json + word_emoji.manifest.json

Same inputs + same model => byte-identical output. Word embeddings are cached under
.cache/, so re-running after a dictionary change only encodes the new words.

    uv run python -m wordbane_emoji.build
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

import numpy as np
from sentence_transformers import SentenceTransformer

# --- pinned knobs (all recorded in the manifest) -----------------------------------
MODEL_ID = "sentence-transformers/all-MiniLM-L6-v2"
REVISION = "c9745ed1d9f207416be6d2e6f8de32d1f16199bf"  # exact HF commit; pins the weights
THRESHOLD = 0.42   # min cosine to accept a word->emoji match; below this we ship nothing.
                   # ~median score: keeps vivid concrete words, drops abstract/function
                   # words to a generic bonk. Confident-but-wrong matches (moon->mooncake)
                   # sit above any usable cutoff; fix those by curating icons.json (wins).
TEMPLATE = "{word}"  # how each word is phrased for the encoder
BATCH = 256

# --- paths -------------------------------------------------------------------------
PKG = Path(__file__).resolve().parent
REPO = PKG.parent.parent                       # emoji_mapper/wordbane_emoji -> repo root
SHARED = REPO / "shared_data"
VOCAB_PATH = PKG.parent / "data" / "emoji_vocab.json"
DICT_PATH = SHARED / "dictionary.json"
OUT_PATH = SHARED / "word_emoji.json"
MANIFEST_PATH = SHARED / "word_emoji.manifest.json"
CACHE = PKG.parent / ".cache"

_WORD = re.compile(r"^[a-z]+$")


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def load_words() -> list[str]:
    raw = json.loads(DICT_PATH.read_text())
    words = raw["words"] if isinstance(raw, dict) else raw
    uniq = {w.lower() for w in words if _WORD.match(w.lower())}
    return sorted(uniq)


def load_vocab() -> tuple[list[str], list[str]]:
    vocab = json.loads(VOCAB_PATH.read_text())
    emojis = sorted(vocab)  # stable order so argmax ties resolve deterministically
    docs = [f"{vocab[e]['name']}. {', '.join(vocab[e]['keywords'])}" for e in emojis]
    return emojis, docs


def embed_words(model: SentenceTransformer, words: list[str]) -> np.ndarray:
    """Encode words, caching per (model, template). Only new words hit the model."""
    CACHE.mkdir(exist_ok=True)
    key = hashlib.sha1(f"{MODEL_ID}|{REVISION}|{TEMPLATE}".encode()).hexdigest()[:12]
    cache_file = CACHE / f"words-{key}.npz"

    cached: dict[str, np.ndarray] = {}
    if cache_file.exists():
        z = np.load(cache_file, allow_pickle=True)
        cached = {w: v for w, v in zip(z["words"].tolist(), z["emb"])}

    missing = [w for w in words if w not in cached]
    if missing:
        print(f"encoding {len(missing)} new words ({len(cached)} cached)...")
        vecs = model.encode(
            [TEMPLATE.format(word=w) for w in missing],
            batch_size=BATCH, normalize_embeddings=True, show_progress_bar=True,
        )
        cached.update(zip(missing, vecs))
        allw = sorted(cached)
        np.savez(cache_file, words=np.array(allw, dtype=object),
                 emb=np.stack([cached[w] for w in allw]))

    return np.stack([cached[w] for w in words])


def main() -> None:
    print(f"loading {MODEL_ID} @ {REVISION[:10]}")
    model = SentenceTransformer(MODEL_ID, revision=REVISION)

    words = load_words()
    emojis, docs = load_vocab()
    print(f"{len(words)} words x {len(emojis)} emoji")

    emoji_mat = model.encode(docs, batch_size=BATCH, normalize_embeddings=True)
    word_mat = embed_words(model, words)

    sims = word_mat @ emoji_mat.T            # (W x E) cosine, both normalized
    best = sims.argmax(axis=1)
    scores = sims[np.arange(len(words)), best]

    mapping = {
        w: emojis[int(best[i])]
        for i, w in enumerate(words)
        if scores[i] >= THRESHOLD
    }
    mapping = dict(sorted(mapping.items()))

    OUT_PATH.write_text(json.dumps({
        "_note": "GENERATED by emoji_mapper (wordbane_emoji.build). Do not hand-edit; "
                 "curate shared_data/icons.json instead, which wins over this file.",
        "_manifest": MANIFEST_PATH.name,
        "words": mapping,
    }, ensure_ascii=False, indent=0, sort_keys=False) + "\n", encoding="utf-8")

    coverage = round(len(mapping) / len(words), 4)
    MANIFEST_PATH.write_text(json.dumps({
        "model_id": MODEL_ID,
        "revision": REVISION,
        "embedding_dim": int(word_mat.shape[1]),
        "template": TEMPLATE,
        "threshold": THRESHOLD,
        "dictionary_sha256_16": _sha(DICT_PATH),
        "emoji_vocab_sha256_16": _sha(VOCAB_PATH),
        "emoji_count": len(emojis),
        "word_count": len(words),
        "mapped_count": len(mapping),
        "coverage": coverage,
    }, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    print(f"mapped {len(mapping)}/{len(words)} ({coverage:.0%}) -> {OUT_PATH.name}")


if __name__ == "__main__":
    main()
